name: Gold Price Auto Scraper 

on:
  schedule:
    - cron: "0 1,3,6,8,11 * * 1-6"  
    # Runs at 08:00, 10:30, 13:00, 15:30, and 18:00 GMT+7 (Converted to UTC)
    # Runs on Monday to Saturday  (0 = Sunday)

  workflow_dispatch:  # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.12"

      - name: Install dependencies
        run: pip install -r ./scrapping/requirements.txt

      - name: Run script
        run: python ./scrapping/main.py

      - name: Check for changes
        run: git status

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update gold price data" || exit 0
          git push https://x-access-token:${GH_TOKEN}@github.com/TruongNguyen0104/goldPrice.git
